controller_mode: "RL"
controller_type: "PPO"

UPPER_VALVE_PIN: 5
LOWER_VALVE_PIN: 6
PUMP_PIN: 4

network_arg:
  input_dim: 2
  com_hidden_dim: 128
  com_layer_num: 1
  low_feature_dim: 64
  head_hidden_dim: 64
  head_layer_num: 1
  action_output_dim: 2
  value_output_dim: 1

lr:
  common: 0.0001
  critic: 0.0003
  actor: 0.0001

pum_max_speed: 36.0

update_arg:
  GAMMA: 0.99
  LAMBDA: 0.95
  epoches: 16
  batch_size: 256
  epsilon: 0.2
  beta: 0.001
